version: "3.9"

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_container
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags      
      - ./utils:/opt/airflow/utils    
      - ./logs:/opt/airflow/logs      
